In [25]:
from common import data_dir
import pandas as pd

cytof = pd.read_csv(data_dir / "cytof.csv", index_col=0)
median_phospho = pd.read_csv("median_phospho_data.csv")

In [26]:
cytof["treatment"] = cytof["simulationConditionId"].apply(lambda x: x.split("__")[1])

In [27]:
cytof_wide = cytof.pivot_table(
    index=["preequilibrationConditionId", "time", "treatment"],
    columns="FEATURE_ID",
    values="measurement",
    aggfunc="mean",
).reset_index()

In [28]:
cytof_wide

FEATURE_ID,preequilibrationConditionId,time,treatment,CyclinB,GAPDH,IdU,Ki.67,b.CATENIN,cleavedCas,glob_cellID,...,p.S6,p.S6K,p.SMAD23,p.SRC,p.STAT1,p.STAT3,p.STAT5,p.p38,p.p53,p.p90RSK
0,c184A1,0.0,EGF,1.899881,2.671202,5.155996,2.293709,1.199649,2.442617,NaN,...,4.618838,1.929640,2.153790,1.945752,2.214089,1.885904,1.681979,1.935045,1.506615,2.607857
1,c184A1,0.0,iEGFR,2.129770,3.274776,5.079816,2.492008,1.553474,2.756784,NaN,...,3.610349,1.796444,2.555733,1.917127,2.201766,2.187779,1.694720,1.794028,1.615741,2.664639
2,c184A1,0.0,iMEK,1.825942,2.769704,5.653566,2.236123,1.212558,2.289400,NaN,...,4.454244,1.519570,2.053051,1.673044,1.902996,1.892970,1.509059,1.532990,1.420732,2.177284
3,c184A1,0.0,iPI3K,1.988940,2.994210,4.976572,2.371744,1.412138,2.536350,NaN,...,4.240250,1.461923,2.400218,1.614901,1.806303,2.033787,1.358842,1.539909,1.440994,2.492932
4,c184A1,0.0,iPKC,1.972291,2.983240,5.060254,2.302046,1.287039,2.500013,NaN,...,3.311478,1.781660,2.298305,1.859048,2.100226,1.957866,1.653499,1.778449,1.471392,2.532473
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2406,cZR7530,60.0,iMEK,2.241898,2.862083,6.450894,3.416233,0.972740,2.572759,NaN,...,7.078829,2.432550,1.951929,2.279354,3.019772,1.685967,2.828684,2.975604,2.567286,4.003108
2407,cZR7530,60.0,iPI3K,2.033617,2.581914,5.816835,3.341244,0.811569,2.139111,NaN,...,4.695991,2.312402,1.718361,2.184490,2.868102,1.539861,2.766841,2.581305,2.370389,4.172435
2408,cZR7530,60.0,iPKC,2.147504,2.701872,5.700462,3.314085,0.897320,2.296849,NaN,...,5.827772,2.455991,1.824923,2.125753,2.990553,1.554868,2.759556,2.704668,2.377929,4.361144
2409,cZR7530__full,0.0,full,2.356754,2.770194,7.013708,3.745414,0.838877,2.126829,NaN,...,5.747266,2.243705,1.769182,2.124122,2.735565,1.602291,2.861731,1.643630,2.353927,4.153167
2410,cZR75B__full,0.0,full,2.772450,2.940417,7.244709,3.692342,0.873703,2.111673,NaN,...,6.236910,1.842559,1.763646,2.744468,2.878489,2.572472,3.003965,2.319315,2.907582,2.910665

In [29]:
median_phospho

,cell_line,treatment,time,b.CATENIN,cleavedCas,CyclinB,GAPDH,IdU,Ki.67,p.4EBP1,...,p.PDPK1,p.PLCg2,p.RB,p.S6,p.S6K,p.SMAD23,p.SRC,p.STAT1,p.STAT3,p.STAT5
0,184A1,EGF,0.0,1.242677,2.522134,1.693038,2.768195,5.048951,1.978325,1.848613,...,2.347183,1.612272,4.559055,4.535059,2.005021,2.275624,1.926817,2.256196,1.898556,1.757215
1,184A1,EGF,5.5,1.071111,2.525901,1.660883,3.063371,5.024605,2.065876,1.638560,...,2.536716,1.675873,4.170496,4.656043,2.301348,2.173578,1.798355,2.279188,2.345774,2.189004
2,184A1,EGF,7.0,1.121240,2.603469,1.693291,3.143739,5.004796,2.148887,1.669925,...,2.627577,1.783505,4.199980,4.787607,2.364732,2.230305,1.804816,2.317053,2.616184,2.316363
3,184A1,EGF,9.0,1.304267,2.808688,1.848270,3.356148,4.966733,2.270448,1.882485,...,2.821235,2.073577,4.431711,4.696978,2.497817,2.457616,1.912574,2.436406,2.977463,2.460209
4,184A1,EGF,13.0,1.218953,2.642353,1.755241,3.219771,4.982155,2.130930,1.695485,...,2.637170,2.119112,4.344876,4.906663,2.434111,2.329397,1.910402,2.441506,2.821463,2.504858
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2334,ZR7530,iPKC,13.0,0.764081,2.423208,1.998027,2.673048,5.679953,2.896984,2.960302,...,2.012969,2.827107,4.069318,5.523754,2.498154,1.881523,2.243195,2.919001,1.458060,2.855371
2335,ZR7530,iPKC,17.0,0.781743,2.414216,1.977245,2.722606,5.618890,2.969602,2.925971,...,2.026573,2.843838,4.024082,5.497454,2.498179,1.893766,2.218456,2.924155,1.477177,2.844739
2336,ZR7530,iPKC,40.0,0.820767,2.440740,2.036949,2.818722,5.394617,3.242962,3.036014,...,2.135887,2.959716,3.745323,5.448678,2.586294,1.978186,2.220442,3.015465,1.558425,2.803418
2337,ZR7530,iPKC,60.0,0.839792,2.438481,2.056416,2.840697,5.322756,3.306419,3.037105,...,2.145124,2.965683,3.660652,5.636240,2.613218,1.984223,2.234943,3.052607,1.586619,2.806520
2338,ZR75B,full,0.0,0.793309,2.136842,2.531233,3.009793,6.140302,3.662012,3.257238,...,1.733651,NaN,5.768492,6.658976,1.935627,1.793562,2.861304,2.947758,2.593895,3.056968

In [48]:
cytof_egf_zero = cytof_wide[(cytof_wide.treatment == "EGF") & (cytof_wide.time == 0)]
cytof_egf_zero.drop(columns=["glob_cellID"], inplace=True)
cytof_egf_zero.rename(columns={"preequilibrationConditionId": "cell_line"}, inplace=True)
cytof_egf_zero.set_index("cell_line", inplace=True)
cytof_egf_zero.sort_index(inplace=True)
cytof_egf_zero

/var/folders/qq/j5fqpnkx00n96n4y5_rx_f7r0000gp/T/ipykernel_65542/3512370148.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cytof_egf_zero.drop(columns=["glob_cellID"], inplace=True)
/var/folders/qq/j5fqpnkx00n96n4y5_rx_f7r0000gp/T/ipykernel_65542/3512370148.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cytof_egf_zero.rename(columns={"preequilibrationConditionId": "cell_line"}, inplace=True)

FEATURE_ID,time,treatment,CyclinB,GAPDH,IdU,Ki.67,b.CATENIN,cleavedCas,p.4EBP1,p.AKT.Thr308.,...,p.S6,p.S6K,p.SMAD23,p.SRC,p.STAT1,p.STAT3,p.STAT5,p.p38,p.p53,p.p90RSK
cell_line,,,,,,,,,,,,,,,,,,,,,
c184A1,0.0,EGF,1.899881,2.671202,5.155996,2.293709,1.199649,2.442617,2.145631,2.308309,...,4.618838,1.929640,2.153790,1.945752,2.214089,1.885904,1.681979,1.935045,1.506615,2.607857
c184B5,0.0,EGF,2.229413,1.863406,6.515773,2.303428,0.787387,2.514049,2.174009,2.095415,...,3.783784,1.738220,1.947752,2.092761,2.256239,1.572773,2.097158,2.075406,1.629602,2.214235
cAU565,0.0,EGF,1.858825,1.592809,6.398712,3.056421,0.789467,2.034115,2.315406,2.184240,...,5.239368,2.413319,1.715545,1.898344,2.435715,1.197309,2.215717,1.823501,3.753488,3.801912
cBT20,0.0,EGF,2.371916,2.203818,6.286955,2.892897,1.070486,2.322998,3.069261,2.654906,...,5.540666,2.306115,2.128813,2.797962,2.961399,2.065865,3.010515,2.568895,2.277523,4.068627
cBT474,0.0,EGF,1.928122,3.061742,6.299717,2.596004,1.157233,2.495332,2.847608,2.891991,...,5.994547,2.070905,1.849810,2.496339,3.270356,1.365461,2.746673,1.793820,2.017150,2.804703
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
cUACC3199,0.0,EGF,2.674187,3.472258,6.777709,3.047506,1.157727,2.456060,3.623581,2.153879,...,5.955307,2.655799,2.237028,2.886675,3.598746,2.072627,2.674704,3.394829,2.056779,4.728141
cUACC812,0.0,EGF,2.059891,1.893330,7.143107,2.865756,0.563627,1.944424,2.062355,1.871264,...,5.120717,1.516097,1.301363,2.273543,1.914984,2.081337,2.484445,2.048050,1.724437,3.268171
cUACC893,0.0,EGF,2.524660,2.218216,7.320930,3.295329,0.975277,1.865113,3.478816,2.305378,...,5.652012,1.851553,1.397550,0.900337,2.060883,0.937772,1.795963,1.010050,2.110479,2.017198
cZR751,0.0,EGF,2.157345,2.543336,5.845301,3.215538,0.812465,2.200662,3.059283,2.389046,...,4.705437,1.932735,1.552694,2.928094,2.539481,2.530901,2.755350,1.861098,2.428498,3.777753
cZR7530,0.0,EGF,2.084200,2.543244,5.998662,3.343965,0.825976,2.185901,2.862318,2.247832,...,5.643314,2.305489,1.752623,2.216758,2.762115,1.538016,2.761331,1.685817,2.443683,4.115311

In [66]:
median_phospho_egf_zero = median_phospho[(median_phospho.treatment == "EGF") & (median_phospho.time == 0)]
median_phospho_egf_zero["cell_line"] = median_phospho_egf_zero["cell_line"].apply(lambda x: "c"+x)
median_phospho_egf_zero.set_index("cell_line", inplace=True)
median_phospho_egf_zero.sort_index(inplace=True)

/var/folders/qq/j5fqpnkx00n96n4y5_rx_f7r0000gp/T/ipykernel_65542/261912817.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  median_phospho_egf_zero["cell_line"] = median_phospho_egf_zero["cell_line"].apply(lambda x: "c"+x)
/var/folders/qq/j5fqpnkx00n96n4y5_rx_f7r0000gp/T/ipykernel_65542/261912817.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  median_phospho_egf_zero.sort_index(inplace=True)

In [70]:
markers = [col for col in cytof_egf_zero.columns if col not in ["preequilibrationConditionId", "time", "treatment"]]

In [71]:
diffs = {}
for marker in markers:
    if marker not in median_phospho_egf_zero.columns:
        print(marker)
    else:
        diffs[marker] = cytof_egf_zero[marker].values - median_phospho_egf_zero[marker].values

In [76]:
pd.DataFrame(diffs, index=median_phospho_egf_zero.index).abs()

,CyclinB,GAPDH,IdU,Ki.67,b.CATENIN,cleavedCas,p.4EBP1,p.AKT.Thr308.,p.AMPK,p.Akt.Ser473.,...,p.S6,p.S6K,p.SMAD23,p.SRC,p.STAT1,p.STAT3,p.STAT5,p.p38,p.p53,p.p90RSK
cell_line,,,,,,,,,,,,,,,,,,,,,
c184A1,0.206843,0.096993,0.107046,0.315384,0.043028,0.079517,0.297018,0.112817,0.042662,0.068757,...,0.083778,0.075381,0.121834,0.018936,0.042106,0.012651,0.075236,0.017731,0.066706,0.035861
c184B5,0.264768,0.022294,0.401069,0.374012,0.155726,0.005025,0.263547,0.001487,0.035421,0.075303,...,0.078713,0.045688,0.031433,0.039259,0.068360,0.103331,0.064363,0.043323,0.073344,0.015101
cAU565,0.225485,0.015547,0.825931,0.082172,0.097489,0.003454,0.028341,0.028977,0.085764,NaN,...,NaN,0.122601,0.027725,0.063061,0.107631,0.213796,0.102083,0.018718,0.245022,0.137685
cBT20,0.298022,0.052577,0.529165,0.243469,0.000611,0.050026,0.099474,0.072519,0.015365,0.072883,...,0.078586,0.066486,0.063614,0.083835,0.011063,0.005515,0.043537,0.060714,0.028430,0.044088
cBT474,0.162803,0.038357,0.288873,0.459397,0.014037,0.047416,0.070626,0.062131,0.047954,0.164318,...,0.226150,0.082377,0.043016,0.087704,0.055672,0.104250,0.065104,0.050891,0.024624,0.025935
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
cUACC3199,0.235662,0.092263,0.959900,0.417091,0.017132,0.069465,0.141949,0.058338,0.058819,0.089884,...,0.112250,0.106467,0.116408,0.110828,0.046969,0.023376,0.052480,0.084681,0.047935,0.181231
cUACC812,0.275637,0.011130,0.958317,0.279391,0.196217,0.042797,0.074640,0.047463,0.146626,0.150993,...,0.192479,0.027827,0.096905,0.032968,0.169961,0.184244,0.176658,0.064878,0.049639,0.106349
cUACC893,0.208920,0.131100,1.258670,0.116849,0.178653,0.145180,0.273023,0.181901,0.077658,0.145992,...,0.192749,0.160769,0.113794,0.011611,0.004592,0.150335,0.091634,0.034181,0.105973,0.102942
cZR751,0.174887,0.041248,0.393044,0.279587,0.072432,0.011781,0.064889,0.034682,0.051285,0.004853,...,0.280284,0.075189,0.004775,0.119735,0.079008,0.026477,0.085072,0.045744,0.068759,0.109187
cZR7530,0.163089,0.079337,0.424286,0.129833,0.111102,0.063755,0.090292,0.055283,0.064648,0.069739,...,0.110396,0.099183,0.049629,0.101919,0.063750,0.039065,0.043770,0.063301,0.091082,0.056961